import type { LocationConfig, LocationId, TasteTag } from "./types";

const defaultTaste = (over: Partial<Record<TasteTag, number>> = {}): Record<TasteTag, number> => ({
  western: 1,
  japanese: 1,
  cafe: 1,
  value: 1,
  formal: 0.6,
  ...over,
});

/** 一代 16 地点（东京），参数按旧攻略客层还原 */
export const LOCATIONS: Record<LocationId, LocationConfig> = {
  kiba: {
    id: "kiba",
    name: "木场",
    rent: 900,
    footfall: 0.85,
    tasteWeights: defaultTaste({ value: 1.4, cafe: 1.2, formal: 0.4 }),
    budgetMul: 0.95,
    relocateCash: 0,
    relocateStars: 0,
    sizeLabel: "10坪",
    blurb: "离车站稍远，路人不多，房租便宜。附近有软件公司。",
    luxuryNeed: 0.15,
    trendNeed: 0.2,
    cleanNeed: 0.35,
  },
  takadanobaba: {
    id: "takadanobaba",
    name: "高田马场",
    rent: 2200,
    footfall: 1.55,
    tasteWeights: defaultTaste({ value: 1.9, cafe: 1.4, formal: 0.35, western: 1.1 }),
    budgetMul: 0.8,
    relocateCash: 45000,
    relocateStars: 1,
    sizeLabel: "27坪",
    blurb: "车站附近，补习班与公司多。学生与上班族为主，高档装潢易反效果。",
    luxuryNeed: 0.2,
    trendNeed: 0.35,
    cleanNeed: 0.4,
  },
  akihabara: {
    id: "akihabara",
    name: "秋叶原",
    rent: 2600,
    footfall: 1.4,
    tasteWeights: defaultTaste({ value: 1.5, western: 1.2, formal: 0.3 }),
    budgetMul: 0.9,
    relocateCash: 55000,
    relocateStars: 2,
    sizeLabel: "23坪",
    blurb: "电气街内，行人多，客层以男性为主，几乎不要求高级感。",
    luxuryNeed: 0.1,
    trendNeed: 0.25,
    cleanNeed: 0.35,
  },
  shinbashi: {
    id: "shinbashi",
    name: "新桥",
    rent: 2800,
    footfall: 1.35,
    tasteWeights: defaultTaste({ western: 1.15, value: 1.3, formal: 0.5 }),
    budgetMul: 1.05,
    relocateCash: 60000,
    relocateStars: 2,
    sizeLabel: "27坪",
    blurb: "车站旁饮食街，上班族日夜都有。应避免过度高级与流行。",
    luxuryNeed: 0.25,
    trendNeed: 0.2,
    cleanNeed: 0.4,
  },
  kanda: {
    id: "kanda",
    name: "神田",
    rent: 3000,
    footfall: 1.45,
    tasteWeights: defaultTaste({ formal: 0.9, japanese: 1.2, value: 1.1, cafe: 0.95 }),
    budgetMul: 1.15,
    relocateCash: 75000,
    relocateStars: 2,
    sizeLabel: "28坪",
    blurb: "古书店巷，学生与上班族都有，不必太高级。",
    luxuryNeed: 0.3,
    trendNeed: 0.3,
    cleanNeed: 0.45,
  },
  ginza: {
    id: "ginza",
    name: "银座四丁目",
    rent: 5200,
    footfall: 1.25,
    tasteWeights: defaultTaste({ formal: 1.8, western: 1.4, value: 0.4, cafe: 0.8 }),
    budgetMul: 1.7,
    relocateCash: 140000,
    relocateStars: 4,
    sizeLabel: "21坪",
    blurb: "面向银座之门，客层多样但高级感需求很高。",
    luxuryNeed: 0.9,
    trendNeed: 0.7,
    cleanNeed: 0.7,
  },
  odaiba: {
    id: "odaiba",
    name: "御台场",
    rent: 4200,
    footfall: 1.3,
    tasteWeights: defaultTaste({ cafe: 1.3, western: 1.2, value: 1.0 }),
    budgetMul: 1.25,
    relocateCash: 110000,
    relocateStars: 3,
    sizeLabel: "36坪",
    blurb: "日落大道一角，周末客层多样热闹。",
    luxuryNeed: 0.45,
    trendNeed: 0.55,
    cleanNeed: 0.5,
    weekdayMul: { 0: 1.35, 6: 1.4 },
  },
  aoyama: {
    id: "aoyama",
    name: "青山",
    rent: 4800,
    footfall: 1.35,
    tasteWeights: defaultTaste({ formal: 1.4, western: 1.3, value: 0.6 }),
    budgetMul: 1.45,
    relocateCash: 130000,
    relocateStars: 4,
    sizeLabel: "28坪",
    blurb: "青山大道一级地段，上班族为主，行人多。",
    luxuryNeed: 0.75,
    trendNeed: 0.8,
    cleanNeed: 0.65,
  },
  asakusa: {
    id: "asakusa",
    name: "浅草",
    rent: 2700,
    footfall: 1.4,
    tasteWeights: defaultTaste({ japanese: 1.5, value: 1.2, formal: 0.5 }),
    budgetMul: 1.0,
    relocateCash: 70000,
    relocateStars: 2,
    sizeLabel: "27坪",
    blurb: "老街难得店面，客层杂、平均年龄偏高。",
    luxuryNeed: 0.35,
    trendNeed: 0.25,
    cleanNeed: 0.45,
  },
  ebisu: {
    id: "ebisu",
    name: "惠比寿",
    rent: 5500,
    footfall: 1.5,
    tasteWeights: defaultTaste({ formal: 1.3, western: 1.35, cafe: 1.2, value: 0.7 }),
    budgetMul: 1.5,
    relocateCash: 160000,
    relocateStars: 4,
    sizeLabel: "45坪",
    blurb: "Garden Place 一带，客层多彩，租金贵但值得。",
    luxuryNeed: 0.7,
    trendNeed: 0.65,
    cleanNeed: 0.6,
  },
  kichijoji: {
    id: "kichijoji",
    name: "吉祥寺",
    rent: 3600,
    footfall: 1.5,
    tasteWeights: defaultTaste({ cafe: 1.35, value: 1.2, western: 1.1 }),
    budgetMul: 1.15,
    relocateCash: 95000,
    relocateStars: 3,
    sizeLabel: "30坪",
    blurb: "商店街与百货附近，平日假日人都很多。",
    luxuryNeed: 0.4,
    trendNeed: 0.5,
    cleanNeed: 0.5,
  },
  shibuya: {
    id: "shibuya",
    name: "涉谷",
    rent: 4000,
    footfall: 1.65,
    tasteWeights: defaultTaste({ cafe: 1.5, value: 1.4, western: 1.2, formal: 0.4 }),
    budgetMul: 1.05,
    relocateCash: 100000,
    relocateStars: 3,
    sizeLabel: "32坪",
    blurb: "年轻人聚集地，务必注意清洁。",
    luxuryNeed: 0.35,
    trendNeed: 0.75,
    cleanNeed: 0.9,
  },
  otemachi: {
    id: "otemachi",
    name: "大手町",
    rent: 4500,
    footfall: 1.2,
    tasteWeights: defaultTaste({ formal: 1.5, western: 1.25, value: 0.7 }),
    budgetMul: 1.4,
    relocateCash: 120000,
    relocateStars: 3,
    sizeLabel: "34坪",
    blurb: "典型办公商圈，平日与假日流量极端，洽公客多。",
    luxuryNeed: 0.55,
    trendNeed: 0.35,
    cleanNeed: 0.55,
    weekdayMul: { 0: 0.45, 6: 0.5 },
  },
  roppongi: {
    id: "roppongi",
    name: "六本木",
    rent: 3800,
    footfall: 1.4,
    tasteWeights: defaultTaste({ formal: 1.6, western: 1.4, value: 0.5, cafe: 1.1 }),
    budgetMul: 1.55,
    relocateCash: 115000,
    relocateStars: 4,
    sizeLabel: "30坪",
    blurb: "再晚也有客人。对流行敏感，高级感要求高。",
    luxuryNeed: 0.85,
    trendNeed: 0.9,
    cleanNeed: 0.65,
  },
  ikebukuro: {
    id: "ikebukuro",
    name: "池袋",
    rent: 3400,
    footfall: 1.6,
    tasteWeights: defaultTaste({ value: 1.5, cafe: 1.35, western: 1.15, formal: 0.45 }),
    budgetMul: 0.95,
    relocateCash: 90000,
    relocateStars: 3,
    sizeLabel: "29坪",
    blurb: "阳光城对面，年轻人占绝大多数，客源有保证。",
    luxuryNeed: 0.3,
    trendNeed: 0.6,
    cleanNeed: 0.55,
  },
  shinjuku: {
    id: "shinjuku",
    name: "新宿西口",
    rent: 4800,
    footfall: 1.7,
    tasteWeights: defaultTaste({ western: 1.2, japanese: 1.1, value: 1.15, formal: 1.0, cafe: 1.1 }),
    budgetMul: 1.2,
    relocateCash: 125000,
    relocateStars: 3,
    sizeLabel: "37坪",
    blurb: "百货二楼人流极大，客层杂；周二公休人数大减。",
    luxuryNeed: 0.5,
    trendNeed: 0.55,
    cleanNeed: 0.55,
    weekdayMul: { 2: 0.35 },
  },
};

export const LOCATION_ORDER: LocationId[] = [
  "kiba",
  "takadanobaba",
  "akihabara",
  "shinbashi",
  "kanda",
  "asakusa",
  "ikebukuro",
  "kichijoji",
  "shibuya",
  "otemachi",
  "odaiba",
  "shinjuku",
  "aoyama",
  "roppongi",
  "ginza",
  "ebisu",
];

export function getLocation(id: LocationId): LocationConfig {
  return LOCATIONS[id] ?? LOCATIONS.kiba;
}

export function pickTaste(weights: Record<TasteTag, number>): TasteTag {
  const entries = Object.entries(weights) as [TasteTag, number][];
  const total = entries.reduce((s, [, w]) => s + w, 0);
  let r = Math.random() * total;
  for (const [tag, w] of entries) {
    r -= w;
    if (r <= 0) return tag;
  }
  return "value";
}

/** 美食历：每月约 30 天；weekday 0=日 */
export function calendarFromDay(day: number): { year: number; month: number; date: number; weekday: number } {
  const idx = Math.max(0, day - 1);
  const year = Math.floor(idx / 360) + 1;
  const month = (Math.floor(idx / 30) % 12) + 1;
  const date = (idx % 30) + 1;
  const weekday = idx % 7;
  return { year, month, date, weekday };
}

/** 营业时段客流权重（对齐一代 time1–time5） */
export function timeOfDayFootfall(minute: number): number {
  if (minute < 11 * 60 + 30) return 0.35;
  if (minute < 14 * 60) return 1.8;
  if (minute < 18 * 60 + 30) return 0.7;
  if (minute < 22 * 60) return 1.55;
  return 0.4;
}
